[package]
name = "wiztree_diff"
version = "0.1.0"
edition = "2021"

[lib]
name = "wiztree_diff_lib"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
